const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { configuration } = require('../server/config.cjs');
const { openStore } = require('../server/store.cjs');
const { createApp } = require('../server/app.cjs');
const { createMessages } = require('../server/messages.cjs');
(async () => {
  const config = configuration({ PUBLIC_URL: 'http://localhost:3000' });
  const db = openStore(':memory:');
  const delivered = [];
  let reject = false;
  const messages = createMessages({ db, mailer: { send: async message => {
    if (reject) throw Object.assign(new Error('Simulated SMTP authentication failure'), { code: 'EAUTH' });
    delivered.push(message);
  } } });
  const server = createApp({ config, db, messages, provider: {} });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  config.publicUrl = base;
  const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true });
  try {
    const context = await browser.newContext({ reducedMotion: 'reduce' });
    await context.route('https://**/*', route => route.abort());
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    for (const [route,id] of [['deraedge-contact/index.html','contact-form'],['deraedge-partnership/index.html','partner-form']]) {
      const before = delivered.length;
      await page.goto(`${base}/${route}`);
      const form = page.locator(`#${id}`);
      await form.locator('[type="submit"]').click();
      assert.equal(await form.locator('.email-preview').isVisible(), false);
      for (const input of await form.locator('input[required],textarea[required]').all()) await input.fill(await input.getAttribute('type') === 'email' ? 'customer@example.com' : 'Customer details');
      if (id === 'partner-form') {
        const country = form.locator('#country');
        assert.equal(await country.evaluate(el => el.tagName), 'SELECT');
        assert.equal(await country.locator('option').count(), 250);
        await page.locator('#contribution-row button').first().click();
        if (await country.evaluate(el => el.tagName === 'SELECT')) {
          await form.locator('[type="submit"]').click();
          assert.equal(await form.locator('.email-preview').isVisible(), false, 'A country must be selected');
          await country.selectOption({ label: 'Nigeria' });
        } else await country.fill('Nigeria');
      }
      await form.locator('[type="submit"]').click();
      assert.equal(delivered.length, before, 'Review cannot send mail');
      assert.match(await form.locator('.email-preview textarea').inputValue(), /okolochinedu10@gmail\.com/);
      if (id === 'partner-form') assert.match(await form.locator('.email-preview textarea').inputValue(), /Country \/ Jurisdiction: Nigeria/);
      // Capture the handoff locally: never open WhatsApp or send a real message.
      await page.evaluate(() => { window.open = url => { window.whatsappDraftUrl = url; }; });
      await form.getByRole('button', { name: 'Open in WhatsApp', exact: true }).click();
      const whatsappUrl = new URL(await page.evaluate(() => window.whatsappDraftUrl));
      assert.equal(whatsappUrl.origin + whatsappUrl.pathname, 'https://wa.me/2347038073238');
      assert.match(whatsappUrl.searchParams.get('text'), /customer@example.com/);
      assert.match(whatsappUrl.searchParams.get('text'), /Customer details/);
      assert.equal(delivered.length, before, 'WhatsApp handoff must not trigger email');
      await form.getByRole('button', { name: 'Edit message', exact: true }).click();
      assert.equal(await form.locator('.email-preview').isVisible(), false);
      await form.locator('textarea:not([readonly])').first().fill('Long message automatically sent. '.repeat(200));
      await form.locator('[type="submit"]').click();
      await form.getByRole('button', { name: 'Open in WhatsApp', exact: true }).click();
      assert.equal(await page.evaluate(() => window.whatsappDraftUrl), 'https://wa.me/2347038073238');
      assert.match(await form.locator('.form-status').textContent(), /Copy message/);
      await form.locator('.chip').last().click();
      assert.equal(await form.locator('.email-preview').isVisible(), false);
      await form.locator('[type="submit"]').click();
      await page.setViewportSize({ width: 375, height: 812 });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
      const original = page.url();
      await form.getByRole('button', { name: 'Send message', exact: true }).click();
      await page.waitForFunction(id => document.querySelector(`#${id} .form-status`).textContent.includes('was sent to'), id);
      assert.equal(page.url(), original, 'Sending must not open an email app');
      assert.equal(delivered.length, before + 1);
      assert.match(delivered.at(-1).text, /Long message automatically sent/);
      if (id === 'partner-form') assert.match(delivered.at(-1).text, /Country: Nigeria/);
      assert.equal(await form.locator('#email').inputValue(), 'customer@example.com');
      assert.equal(await form.getByRole('button', { name: 'Send message', exact: true }).isDisabled(), true);
      await page.reload();
      await page.waitForFunction(id => document.querySelector(`#${id} .form-status`).textContent.includes('was sent to'), id);
      assert.equal(delivered.length, before + 1, 'Reload must not send twice');
      assert.equal(await form.getByRole('button', { name: 'Open in WhatsApp', exact: true }).isDisabled(), true, 'Reload must not expose a stale WhatsApp draft');
      await page.setViewportSize({ width: 1280, height: 900 });
    }
    reject = true;
    await page.goto(`${base}/deraedge-contact/index.html`);
    await page.waitForFunction(() => document.querySelector('#contact-form .form-status').textContent.includes('was sent to'));
    await page.getByRole('button', { name: 'Write another message' }).click();
    await page.fill('#name','Customer'); await page.fill('#email','customer@example.com'); await page.fill('#message','Test failure handling');
    await page.getByRole('button', { name: 'Review Enquiry' }).click();
    await page.getByRole('button', { name: 'Send message', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#contact-form .form-status').textContent.includes('could not accept'));
    assert.equal(await page.locator('#message').inputValue(),'Test failure handling');
    assert.equal(await page.getByRole('button', { name: 'Send message', exact: true }).isEnabled(), true);
    assert.equal(delivered.length, 2);
    assert.equal(await page.locator('.email-preview .form-status').isVisible(), true);
    reject = false;
    await page.getByRole('button', { name: 'Send message', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#contact-form .form-status').textContent.includes('was sent to'));
    assert.equal(delivered.length, 3, 'A confirmed failure can be retried directly with Send message');
    assert.equal(await page.getByRole('button', { name: 'Send message', exact: true }).isDisabled(), true);
    await page.evaluate(() => sessionStorage.clear());
    await page.route('**/api/messages/config', route => route.fulfill({ json: { enabled: false } }));
    await page.goto(`${base}/deraedge-contact/index.html`);
    await page.fill('#name','Customer'); await page.fill('#email','customer@example.com'); await page.fill('#message','WhatsApp without email');
    await page.getByRole('button', { name: 'Review Enquiry' }).click();
    assert.equal(await page.getByRole('button', { name: 'Send message', exact: true }).isDisabled(), true);
    assert.equal(await page.getByRole('button', { name: 'Open in WhatsApp', exact: true }).isEnabled(), true);
    assert.deepEqual(errors, []);
    console.log('PASS: both review-to-send flows, automatic delivery, long messages, recipient contents, no email app, reload deduplication, SMTP failure, preserved inputs, and mobile layout. Mock transport only: no real emails sent.');
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); await messages.stop(); db.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
